[ 28/04/2024-12:15:01 ] [ _.Http._ ] Erro ao autenticar um usuário : "Error: DataSource is not set for this entity.
    at Function.getRepository (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:116:19)
    at Function.findOne (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:544:21)
    at Object.run (C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\Routers\Auth\Login.ts:28:28)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\StructuralHttp.ts:95:30
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:346:12)"
[ 28/04/2024-12:16:13 ] [ _.Http._ ] Erro ao autenticar um usuário : "Error: DataSource is not set for this entity.
    at Function.getRepository (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:116:19)
    at Function.findOne (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:544:21)
    at Object.run (C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\Routers\Auth\Login.ts:28:28)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\StructuralHttp.ts:95:30
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:346:12)"
[ 28/04/2024-12:16:21 ] [ _.Http._ ] Erro ao autenticar um usuário : "Error: DataSource is not set for this entity.
    at Function.getRepository (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:116:19)
    at Function.findOne (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:544:21)
    at Object.run (C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\Routers\Auth\Login.ts:28:28)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\StructuralHttp.ts:95:30
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:346:12)"
[ 28/04/2024-12:20:00 ] [ _.Http._ ] Erro ao autenticar um usuário : "Error: DataSource is not set for this entity.
    at Function.getRepository (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:116:19)
    at Function.findOne (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:544:21)
    at Object.run (C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\Routers\Auth\Login.ts:28:28)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\StructuralHttp.ts:96:30
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:346:12)"
[ 28/04/2024-12:20:29 ] [ _.Http._ ] Erro ao autenticar um usuário : "Error: DataSource is not set for this entity.
    at Function.getRepository (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:116:19)
    at Function.findOne (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:544:21)
    at Object.run (C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\Routers\Auth\Login.ts:28:28)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\StructuralHttp.ts:98:30
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:346:12)"
[ 28/04/2024-12:21:30 ] [ _.Http._ ] Erro ao autenticar um usuário : "Error: DataSource is not set for this entity.
    at Function.getRepository (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:116:19)
    at Function.findOne (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:544:21)
    at Object.run (C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\Routers\Auth\Login.ts:28:28)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\StructuralHttp.ts:98:30
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:346:12)"
[ 28/04/2024-12:21:58 ] [ _.Http._ ] Erro ao autenticar um usuário : "Error: DataSource is not set for this entity.
    at Function.getRepository (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:116:19)
    at Function.findOne (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:544:21)
    at Object.run (C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\Routers\Auth\Login.ts:28:28)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\StructuralHttp.ts:98:30
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:346:12)"
[ 28/04/2024-12:22:33 ] [ _.Http._ ] Erro ao autenticar um usuário : "Error: DataSource is not set for this entity.
    at Function.getRepository (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:116:19)
    at Function.findOne (C:\Users\Drylian\Documents\GitHub\CorePanel\src\repository\BaseEntity.ts:544:21)
    at Object.run (C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\Routers\Auth\Login.ts:28:28)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\app\Http\StructuralHttp.ts:98:30
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\Drylian\Documents\GitHub\CorePanel\node_modules\express\lib\router\index.js:346:12)"
